// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Graphene","status":true,"description":"Create your own ui with html.","parameters":{"uiPath":"graphene-ui-build/index.html","liveDevelopment":"false","address":"http://localhost:5173/"}}
];
