// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"r88_CustomControls","status":true,"description":"Gives you more control over your game's controls.","parameters":{"Up":"[\"w\",\"gpadup\"]","Down":"[\"s\",\"gpaddown\"]","Left":"[\"a\",\"gpadleft\"]","Right":"[\"d\",\"gpadright\"]","Confirm":"[\"e\",\"gpad0\"]","Cancel/Menu":"[\"esc\"]","Sprint":"[\"shift\",\"gpad2\",\"ctrl\"]","Noclip":"[\"n\"]","Cancel":"[\"gpad1\"]","Menu Scene":"[\"gpad3\"]","Item Scene":"[]","Skill Scene":"[]","Equip Scene":"[]","Options Scene":"[]","Save Scene":"[]","Load Scene":"[]","Common Events":"[]","Disable Mouse Controls":"false","Disable UI Buttons":"false"}},
{"name":"SkillsNGuilt","status":true,"description":"Adds a new skills and guilt system","parameters":{}},
{"name":"Graphene","status":true,"description":"Create your own ui with html.","parameters":{"uiPath":"graphene-ui-build/index.html","liveDevelopment":"false","address":"http://localhost:5173/"}}
];
